#!/bin/zsh -l

function run-command() {
    echo "----- $1 -----"
    eval $1
    echo
}

run-command 'brew update'
run-command 'brew outdated'
run-command 'brew cask outdated'
run-command 'brew doctor'

# vim: set filetype=zsh :
