#!/bin/zsh

if [ ! -d .git ]; then
    echo '.git not found'
    echo 'Please execute in git repository root'
    exit 1
fi
stash_dir='/tmp/git-stash-hooks'

set -x

rm -rf $stash_dir
mkdir -p $stash_dir
mv .git/hooks/* $stash_dir

# vim: set filetype=zsh :
