#!/bin/zsh

if [ ! -d .git ]; then
    echo '.git not found'
    echo 'Please execute in git repository root'
    exit 1
fi

set -x
git config --local gc.auto 3000
git config --local gc.pruneExpire '1 weeks ago'
git config --local gc.reflogexpire '30 days'

# vim: set filetype=zsh :
