#!/bin/zsh

if [ ! -d .git ]; then
    echo '.git not found'
    echo 'Please execute in git repository root'
    exit 1
fi
stash_dir='/tmp/git-stash-hooks'
mv_command="mv .git/hooks/* $stash_dir"

rm -rf $stash_dir
mkdir -p $stash_dir
echo $mv_command
eval $mv_command

# vim: set filetype=zsh :
