#!/bin/zsh

test $# -ne 1 && echo 'Please specify an item name.' && exit 1
security find-generic-password -s $1 >& /dev/null
test $? -ne 0 && echo "Specified key '$1' is not found." && exit 1

security 2>&1 >/dev/null find-generic-password -ws $1 | tr -d "\n" | pbcopy

# vim: set filetype=zsh :
