#!/bin/zsh

if [ $# -ne 1 ]; then echo 'Please specify the URL' 1>&2; exit 1; fi
if ! which docker >& /dev/null; then echo 'Docker not found' 1>&2; exit 1; fi
docker run --rm atton/webpage-title $1

# vim: set filetype=zsh :
