#!/bin/zsh

if [ -z "$TMUXINATOR_WORK_HOME" ]; then echo '$TMUXINATOR_WORK_HOME is undefined.' && exit 1; fi
which tmuxinator >& /dev/null
if [ $? -ne 0 ]; then echo 'tmuxinator not found.' && exit 1; fi

tmuxinator work

# vim: set filetype=zsh :
